 //------------------------------------------------------------------------------
 // <auto-generated>
 //     This code was generated by a tool.(The author is Boiling)
 //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 // </auto-generated>
 //------------------------------------------------------------------------------
namespace protocol.client.g2c
{
     public class G2CIdGenerater
     {
          public static void GenerateId()
          {
               Protocol.MsgId.Id<MSG_GC_USER_LOGIN>.Value= 0x110001;
          }
     }
}
