//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Client/Client.proto
namespace protocol.client
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_CG_USER_LOGIN")]
  public partial class MSG_CG_USER_LOGIN : global::ProtoBuf.IExtensible
  {
    public MSG_CG_USER_LOGIN() {}
    
    private string _username;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private string _password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private string _version;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string version
    {
      get { return _version; }
      set { _version = value; }
    }
    private string _deviceId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"deviceId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string deviceId
    {
      get { return _deviceId; }
      set { _deviceId = value; }
    }
    private string _registerId;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"registerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string registerId
    {
      get { return _registerId; }
      set { _registerId = value; }
    }
    private string _channelName;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"channelName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channelName
    {
      get { return _channelName; }
      set { _channelName = value; }
    }
    private int _groupId;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"groupId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int groupId
    {
      get { return _groupId; }
      set { _groupId = value; }
    }
    private string _token;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_GC_USER_LOGIN")]
  public partial class MSG_GC_USER_LOGIN : global::ProtoBuf.IExtensible
  {
    public MSG_GC_USER_LOGIN() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private string _username;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }

    private string _token = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private readonly global::System.Collections.Generic.List<protocol.client.ROLE_INFO> _roleList = new global::System.Collections.Generic.List<protocol.client.ROLE_INFO>();
    [global::ProtoBuf.ProtoMember(4, Name=@"roleList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protocol.client.ROLE_INFO> roleList
    {
      get { return _roleList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_CG_RECONNECT_LOGIN")]
  public partial class MSG_CG_RECONNECT_LOGIN : global::ProtoBuf.IExtensible
  {
    public MSG_CG_RECONNECT_LOGIN() {}
    
    private string _username;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private string _token;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private int _uid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private string _oldBlowFish;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"oldBlowFish", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string oldBlowFish
    {
      get { return _oldBlowFish; }
      set { _oldBlowFish = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_GC_RECONNECT_LOGIN")]
  public partial class MSG_GC_RECONNECT_LOGIN : global::ProtoBuf.IExtensible
  {
    public MSG_GC_RECONNECT_LOGIN() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ROLE_INFO")]
  public partial class ROLE_INFO : global::ProtoBuf.IExtensible
  {
    public ROLE_INFO() {}
    
    private int _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _sex;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private int _modelId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"modelId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int modelId
    {
      get { return _modelId; }
      set { _modelId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_CG_CREATE_ROLE")]
  public partial class MSG_CG_CREATE_ROLE : global::ProtoBuf.IExtensible
  {
    public MSG_CG_CREATE_ROLE() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _sex;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private int _modelId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"modelId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int modelId
    {
      get { return _modelId; }
      set { _modelId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_GC_CREATE_ROLE")]
  public partial class MSG_GC_CREATE_ROLE : global::ProtoBuf.IExtensible
  {
    public MSG_GC_CREATE_ROLE() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private protocol.client.ROLE_INFO _roleInfo;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roleInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public protocol.client.ROLE_INFO roleInfo
    {
      get { return _roleInfo; }
      set { _roleInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}