 //------------------------------------------------------------------------------
 // <auto-generated>
 //     This code was generated by a tool.(The author is Boiling)
 //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 // </auto-generated>
 //------------------------------------------------------------------------------
namespace protocol.client.c2g
{
     public class C2GIdGenerater
     {
          public static void GenerateId()
          {
               Protocol.MsgId.Id<MSG_CG_USER_LOGIN>.Value= 0x110001;
               Protocol.MsgId.Id<MSG_CG_CREATE_CHARACTER>.Value= 0x110002;
          }
     }
}
