//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Client/G2C.proto
namespace protocol.client.g2c
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_GC_USER_LOGIN")]
  public partial class MSG_GC_USER_LOGIN : global::ProtoBuf.IExtensible
  {
    public MSG_GC_USER_LOGIN() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private string _accountName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"accountName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string accountName
    {
      get { return _accountName; }
      set { _accountName = value; }
    }

    private int _token = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int token
    {
      get { return _token; }
      set { _token = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}