//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Client/C2G.proto
namespace protocol.client.c2g
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_CG_USER_LOGIN")]
  public partial class MSG_CG_USER_LOGIN : global::ProtoBuf.IExtensible
  {
    public MSG_CG_USER_LOGIN() {}
    
    private string _accountName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"accountName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string accountName
    {
      get { return _accountName; }
      set { _accountName = value; }
    }
    private string _deviceId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"deviceId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string deviceId
    {
      get { return _deviceId; }
      set { _deviceId = value; }
    }
    private string _version;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string version
    {
      get { return _version; }
      set { _version = value; }
    }
    private string _password;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private int _mainId;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"mainId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mainId
    {
      get { return _mainId; }
      set { _mainId = value; }
    }
    private int _token;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int token
    {
      get { return _token; }
      set { _token = value; }
    }
    private string _registerId;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"registerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string registerId
    {
      get { return _registerId; }
      set { _registerId = value; }
    }
    private string _channelName;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"channelName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channelName
    {
      get { return _channelName; }
      set { _channelName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_CG_CREATE_CHARACTER")]
  public partial class MSG_CG_CREATE_CHARACTER : global::ProtoBuf.IExtensible
  {
    public MSG_CG_CREATE_CHARACTER() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _mainId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mainId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mainId
    {
      get { return _mainId; }
      set { _mainId = value; }
    }
    private int _sex;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private int _head;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"head", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int head
    {
      get { return _head; }
      set { _head = value; }
    }
    private int _systemFashionId;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"systemFashionId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int systemFashionId
    {
      get { return _systemFashionId; }
      set { _systemFashionId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}